---
title: "A short blog on using citations"
output: webexercises::webexercises_default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webexercises")) {
  stop("You must have the 'webexercises' package installed to knit to HTML.\n   install.packages(\"webexercises\")")
} else {
  library("webexercises")
}
```

## Why use Citations

In academic writing, whether it is a report or an essay, it is important that we show where the information and ideas come from, to help distinguish between our own ideas and those that we have read in other people's work. We do this through giving citations in our writing and then supplying a reference section at the end of the work. Look at this paragraph, for example, taken from McAleer and Paterson (2021) (which you can read here [https://psyarxiv.com/q34k8](https://psyarxiv.com/q34k8)) where we have highlighted the citations in bold to make it easier to see them 

**Original paragraph with citations**

"As an illustrative example of the problem, an established way to improve evidence is to normalise replications of studies, collate their findings, and base new pedagogical approaches upon the outcomes. **Alister and colleagues (2021)**, in a survey on practices that gave researchers more confidence in published research, found that a direct replication of a study - using the same methods as the original study - resulted in the greatest increase in confidence to that finding. However, somewhat counterintuitively, published replications are the exception and not the norm. For instance, **Makel et al. (2010)**, based on a review of the top one hundred psychology journals, estimated replications to make up approximately only 1.6% of all published articles. Educational research also has a limited publication record of replications, with **Makel and Plucker (2014)** finding that only 0.13% of studies in the top educational research journals, over a 5-year period, to be replications; this value was reported at 0.5% two years later **(Makel et al., 2016)**. Given the perception of replications as being the gold standard in science, it is perhaps surprising that replications constitute less of the published research over time, not more."

Now look at the same paragraph with the citations removed:

"As an illustrative example of the problem, an established way to improve evidence is to normalise replications of studies, collate their findings, and base new pedagogical approaches upon the outcomes. In a survey on practices that gave researchers more confidence in published research, found that a direct replication of a study - using the same methods as the original study - resulted in the greatest increase in confidence to that finding. However, somewhat counterintuitively, published replications are the exception and not the norm. Based on a review of the top one hundred psychology journals, it was estimated replications make up approximately only 1.6% of all published articles. Educational research also has a limited publication record of replications, with research finding that only 0.13% of studies in the top educational research journals, over a 5-year period, to be replications; this value was reported at 0.5% two years later. Given the perception of replications as being the gold standard in science, it is perhaps surprising that replications constitute less of the published research over time, not more."

**Discussion on the role of citations**

As you can see, what is lacking in the second version of the paragraph above, when we don't give citations, we lose the knowledge of where the information has come from, and when that work was created. It is also now unclear if the original authors are just giving their opinion or stating previous findings, as there is no means to check their claims. To some degree you could say that citations allow us to state information, state supporting evidence, and prompt discussion. Using the above paragraph for example we see:

* **an example of stating information: **this value was reported at 0.5% two years later (Makel et al., 2016)
* **an example of stating supporting evidence: **Alister and colleagues (2021), in a survey on practices that gave researchers more confidence in published research, found that a direct replication of a study - using the same methods as the original study - resulted in the greatest increase in confidence to that finding
* **an example of prompting discussion: **However, somewhat counterintuitively, published replications are the exception and not the norm. For instance, Makel et al. (2010), based on a review of the top one hundred psychology journals, estimated replications to make up approximately only 1.6% of all published articles

So as you can see, citations help validate statements within a piece of work, giving those statements support. Citations allow us as writers to build our work on previous literature and to help generate discussion points that lead our writing on. In addition, citations allow us, as future researchers, to check previous work and to follow the research back in time. In short, to so some degree, citations are the "family tree" of a research question and they help us know where we are going because they show us where we have come from!

## Activity:

To help you think more about where citations should be placed we have this short exercise. In the paragraph below the citations have all been removed. Your task is to simply read the paragraph and think where you would place the citations. The original paragraph is supplied and can be revealed by simply pressing the "Reveal Original Paragraph" button. The paragraph comes from Dawydiak, E. J., Stafford, H. E., Stevenson, J. L., & Jones, B. C. (2019). Pathogen disgust predicts stigmatization of individuals with mental health conditions. Evolutionary Psychological Science, 1-4, which you can access here if you like: [https://link.springer.com/article/10.1007/s40806-019-00208-x](https://link.springer.com/article/10.1007/s40806-019-00208-x) 

Your task, as above, is to read through the paragraph and decide where the citations should be placed. Once you have decided this, click the button below to reveal the original paragraph and to see how you compared.

* **Top Tip: ** Citations should be placed as close as possible to the point being made - either within the sentence or at the end of the sentence - and can be used to supply supporting evidence, state information, and spark discussion.

**Edited Paragraph with citations removed**

People tend to avoid stigmatized individuals, such as those with prominent birthmarks or physical disabilities. People also tend to avoid individuals displaying signs of infectious illnesses, such as facial lesions. Because the costs of false-negative identification when assessing our environment for pathogens are likely greater than the costs of making false-positive identification, researchers have proposed that both types of social avoidance (avoidance of individuals displaying signs of infectious illnesses and stigmatization of other types of individual, e.g., obese individuals) reflect a common underlying mechanism: infectious disease avoidance. In other words, they suggested that the potentially “over inclusive” nature of avoidance of individuals displaying signs of infectious illnesses contributes to the stigmatization of other groups of atypical individuals.

`r hide("Reveal Original Paragraph")`

People tend to avoid stigmatized individuals, such as those with prominent birthmarks or physical disabilities (reviewed in Oaten et al., 2011; Murray and Schaller, 2016). People also tend to avoid individuals displaying signs of infectious illnesses, such as facial lesions (Murray and Schaller, 2016). Because the costs of false-negative identification when assessing our environment for pathogens are likely greater than the costs of making false-positive identification (“the smoke detector principle,” Nesse, 2005), Oaten et al. (2011) proposed that both types of social avoidance (avoidance of individuals displaying signs of infectious illnesses and stigmatization of other types of individual, e.g., obese individuals) reflect a common underlying mechanism: infectious disease avoidance. In other words, Oaten et al. (2011) suggested that the potentially “over inclusive” nature of avoidance of individuals displaying signs of infectious illnesses contributes to the stigmatization of other groups of atypical individuals (see also Kurzban and Leary, 2001; van Leeuwen et al., 2015; Park et al., 2007).

`r unhide()`

**Take-Away Message**

Citations within our writing are very important for showing the background to our work, and all the writing that you do in Psychology will probably have a number of citations. When we give a citation we are acknowledging the previous work that our own work is based on, and we add support to the points we are making. Where to position citations can seem tricky at first - and we will look more at this as we progress - but as close to the point being made as possible is a good starting point.

**Authors of this blog**

This blog was developed by Drs James Bartlett, Phil McAleer, Helena Paterson and Emily Nordmann of the School of Psychology and Neuroscience. All comments are greatly received and should be directed to James, Phil and/or Helena.

